version: '3'

services:
    jupyter-notebook:
        build: ./
        volumes:
            - ${JUPYTER_DIR}:/home/jovyan/work
        ports:
            - "8888:8888"
        environment:
            - JUPYTER_ENABLE_LAB=1
        command: "start-notebook.sh --NotebookApp.token=''"
