version: '3'

services:
    jupyter-notebook:
        image: bg/jupyter-experiment-env:latest
        volumes:
            - ${JUPYTER_DIR}:/home/jovyan/work
        ports:
            - "8888:8888"
        environment:
            - JUPYTER_ENABLE_LAB=1
            - GRANT_SUDO=1
        command: "start-notebook.sh --NotebookApp.token=''"
        tty: true
